[package]
name = "actix-example"
version = "0.1.0"
authors = ["Andreas Molzer <andreas.molzer@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.8"
actix-web = "1.0"
env_logger = "0.6"
futures = "0.1"
oxide-auth = { version = "0.5.0-preview.0", path = "./../../../oxide-auth" }
oxide-auth-actix = { version = "0.0.1", path = "./../../" }
reqwest = "=0.9.5"
serde = "1.0"
serde_json = "1.0"
url = "1.7"
